(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},h=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},k=h(this),m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={g:!0},q={};try{q.__proto__=p;n=q.g;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var r=m,t=function(a,b){a.prototype=f(b.prototype);a.prototype.constructor=a;if(r)r(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.u=b.prototype};var u="abort canplay canplaythrough durationchange emptied ended error loadeddata loadedmetadata loadstart pause play playing progress ratechange seeked seeking stalled suspend timeupdate volumechange waiting".split(" ");var w=function(){var a=HTMLElement.call(this)||this;a.video=null;a.s=0;a.b=function(){v(a,!0)};a.f=function(){return a.handleVideoTimeUpdate()};a.resizeHandlerNeeded=!1;return a};t(w,HTMLElement);w.prototype.connectedCallback=function(){var a=this.parentElement;a&&a.interactiveVideoComponents&&(this.video=a,this.video.interactiveVideoComponents.push(this),this.video.setResizeObserver(),this.video.addEventListener("ended",this.b,!1),this.video.addEventListener("timeupdate",this.f,!1))};
w.prototype.disconnectedCallback=function(){if(this.video&&this.video.interactiveVideoComponents){var a=this.video.interactiveVideoComponents.indexOf(this);-1!=a&&this.video.interactiveVideoComponents.splice(a,1);this.video.setResizeObserver();this.video.removeEventListener("ended",this.b,!1);this.video.removeEventListener("timeupdate",this.f,!1)}this.video=null};w.prototype.resize=function(){};var x=function(a,b){var c=void 0===c?null:c;var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c);b.dispatchEvent(e)},z=function(a,b){var c=function(e){a.removeEventListener("canplay",c);b(e)};a.addEventListener("canplay",c)};var A={l:"show-time",i:"hide-time",j:"left",m:"top",o:"width",h:"height"},B=[],C=0,D;for(D in A)B[C++]=A[D];var E=function(){var a=w.call(this)||this;a.c=function(){return void a.resize()};a.resizeHandlerNeeded=!0;a.a=function(b){return void b.stopPropagation()};return a};t(E,w);d=E.prototype;
d.connectedCallback=function(){w.prototype.connectedCallback.call(this);for(var a=0;a<u.length;a++)this.addEventListener(u[a],this.a,!1);this.video.addEventListener("loadedmetadata",this.c,!1);this.resize();this.handleVideoTimeUpdate()};d.disconnectedCallback=function(){this.video.removeEventListener("loadedmetadata",this.c,!1);w.prototype.disconnectedCallback.call(this);for(var a=0;a<u.length;a++)this.removeEventListener(u[a],this.a,!1)};
d.attributeChangedCallback=function(a){switch(a){case "left":case "top":case "width":case "height":this.resize();break;case "show-time":case "hide-time":this.handleVideoTimeUpdate()}};d.getShowTime=function(){var a=parseFloat(this.getAttribute("show-time"));return isNaN(a)?null:a};d.setShowTime=function(a){null!==a?this.setAttribute("show-time",Math.max(a,0)):this.removeAttribute("show-time")};d.getHideTime=function(){var a=parseFloat(this.getAttribute("hide-time"));return isNaN(a)?null:a};
d.setHideTime=function(a){null!==a?this.setAttribute("hide-time",Math.max(a,this.getShowTime()||0)):this.removeAttribute("hide-time")};d.getLeft=function(){return this.getAttribute("left")||"25%"};d.setLeft=function(a){this.setAttribute("left",a)};d.getTop=function(){return this.getAttribute("top")||"25%"};d.setTop=function(a){this.setAttribute("top",a)};d.getWidth=function(){return this.getAttribute("width")||"50%"};d.setWidth=function(a){this.setAttribute("width",a)};
d.getHeight=function(){return this.getAttribute("height")||"50%"};d.setHeight=function(a){this.setAttribute("height",a)};d.seek=function(a){void 0===a||a?(a=this.getShowTime()||0,this.video.seek(a)):(a=this.getHideTime())?this.video.seek(a):this.video.duration&&this.video.seek(this.video.duration)};d.setTimes=function(a,b){b=void 0===b?null:b;this.setShowTime(a);this.setHideTime(b)};
d.show=function(a){var b=this.querySelector("gwd-video");void 0===a||a?(b&&(b.play?(b.currentTime=0,b.play()):z(b,function(){b.play()})),this.classList.add("visible"),this.querySelector("[data-gwd-fit-font-size]")&&(a=document.body.querySelector("gwd-text-helper"))&&a.refitAll()):(this.classList.remove("visible"),b&&b.pause())};
var v=function(a,b){if(a.video){b=b?Number(Math.round(a.video.duration+"e2")+"e-2"):Math.round(100*a.video.currentTime)/100;var c=a.getShowTime(),e=a.getHideTime();if(a.isVisible()){if(b<(c||0)||null!==e&&b>=e||null!==c&&a.video.paused&&0===b)a.show(!1),x("hotspothidden",a)}else{var g=!1;if(null===c){if(a.video.paused&&0===b||(!a.video.paused||0<b)&&(null===e||b<e))g=!0}else(!a.video.paused||0!==b)&&b>=c&&(null===e||b<e)&&(g=!0);g&&(a.show(!0),x("hotspotshown",a))}}};
E.prototype.handleVideoTimeUpdate=function(){v(this,!1)};
E.prototype.resize=function(){if(this.video){var a=this.video.videoWidth,b=this.video.videoHeight,c=this.video.getBoundingClientRect(),e=c.width;c=c.height;if(e&&c){var g=Math.max(a/e,b/c),l=parseFloat(this.getLeft());this.style.left=50+a/e/g*(l-50)+"%";var y=parseFloat(this.getTop());this.style.top=50+b/c/g*(y-50)+"%";l=Math.min(parseFloat(this.getWidth()),100-l);this.style.width=a/e/g*l+"%";a=Math.min(parseFloat(this.getHeight()),100-y);this.style.height=b/c/g*a+"%"}}};E.prototype.isVisible=function(){return this.classList.contains("visible")};
k.Object.defineProperties(E,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return B}}});customElements.define("gwd-hotspot",E);}).call(this);
